apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce # Consegue ler e escrever no mesmo node.
    - ReadWriteMany # Consegue ler e escrever em diferentes nodes.
